### PR TITLE
Increase test coverage for Event class by 10%

### PR DESCRIPTION
**Pull request by allenporter**
Improve test coverage for `event.py`, getting closer to 90% coverage.
Coverage improvements include duration, gt/lt comparisons, within, includes, and intersects methods.

Issue #245

### CODE REVIEW

**Review by C4ptainCrunch — APPROVED** [review]

**Comment by allenporter** [comment]
Thanks for the review. Is there a path to merging? I'm trying to decide if it's worthwhile to continue to contribute here.  I get the point of merging before applying black but unsure what we're waiting on.

**Comment by C4ptainCrunch** [comment]
@allenporter To me, this is good to merge, i can merge it when you want. But i can also wait if you want to work some more on it :)

**Comment by allenporter** [comment]
> @allenporter To me, this is good to merge, i can merge it when you want. But i can also wait if you want to work some more on it :)

Oh no, to clarify, i'm not saying i'm trying to add more to this PR. It was finished 22 days ago and i'm not sure what the next steps are.  I was planning to add a huge number of tests, but no I'm trying to decide if it's worthwhile to contribute here at all.

**Comment by C4ptainCrunch** [comment]
>I'm trying to decide if it's worthwhile to contribute here at all.

@allenporter You work is appreciated, you can be sure of it ! If you want to write more tests, it will be welcome ❤️

**Comment by strobeflash** [comment]
> Oh no, to clarify, i'm not saying i'm trying to add more to this PR. It was finished 22 days ago and i'm not sure what the next steps are. I was planning to add a huge number of tests, but no I'm trying to decide if it's worthwhile to contribute here at all.

@allenporter Thank you for your contributions! Don't leave me, between your tests and my docs we could achieve great things! :) When could you have your next pull request ready? @C4ptainCrunch, when do you think you'll be able to make time to review? I'll try to have something ready too by then.

**Pull request merged**
