### PR TITLE
AUTHORS.rst typos and dead link

### PR DESCRIPTION
**Pull request by jeertmans**
I just encountered some duplicate and a dead link in the AUTHORS.rst file :)

### CODE REVIEW

**Review by aureooms — APPROVED** [review]

**Comment by N-Coder** [comment]
Hey, thanks for the PR. Could you please sync this with the changes proposed in #242?

**Comment by jeertmans** [comment]
> Hey, thanks for the PR. Could you please sync this with the changes proposed in #242?

Hi, if by "syncing" you meant merging PR #242 into mine, I just did it :)

**Comment by N-Coder** [comment]
It seems like that didn't work, if you look at the file as it is right now. Is there anything new in this PR that hasn't been changed by the other PR yet?

**Comment by jeertmans** [comment]
> It seems like that didn't work, if you look at the file as it is right now. Is there anything new in this PR that hasn't been changed by the other PR yet?

I think my PR is actually sort of a duplicate of #142 .. I checked and this only difference comes in the link for the `arrow` package: I reference the Github page while #142 references the documentation.

**Pull request closed without merging**
